CREATE DATABASE SENAI_HROADS_TARDE;
USE SENAI_HROADS_TARDE;
CREATE TABLE Classes (
	IdClasse INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(50) UNIQUE NOT NULL
);
CREATE TABLE TiposHabilidades (
	IdTipoHabilidade INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(20) NOT NULL UNIQUE
);
CREATE TABLE Habilidades (
	IdHabilidade INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(100) NOT NULL UNIQUE,
	IdTipoHabilidade INT FOREIGN KEY REFERENCES TiposHabilidades(IdTipoHabilidade) NOT NULL
);
CREATE TABLE ClassesHabilidades (
	IdClasse INT NOT NULL FOREIGN KEY REFERENCES Classes(IdClasse),
	IdHabilidade INT FOREIGN KEY REFERENCES Habilidades(IdHabilidade)
);
CREATE TABLE Personagens (
	IdPersonagem INT NOT NULL PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL UNIQUE,
	VidaMax TINYINT NOT NULL,
	ManaMax TINYINT NOT NULL,
	UltimaAtualizacao DATETIME2 NOT NULL,
	Criacao DATETIME2 NOT NULL,
	Classe	INT NOT NULL FOREIGN KEY REFERENCES Classes(IdClasse)
);